-- What was said, and what it was said to mean (postgres profile).
--
-- A meeting already left behind chat, notes, a whiteboard, an agenda, files and
-- a recording. The one thing it did not keep was the part people actually spend
-- the hour doing: talking. The recording holds it, but a recording is not a
-- record — you cannot search it, quote it, or read it in the four minutes
-- somebody has before the next meeting.
--
-- ONLY FINAL UTTERANCES LAND HERE. Speech recognition emits a running guess
-- that changes several times a second and is then replaced; storing those would
-- fill the table with sentences nobody ever said. Interim results are relayed
-- to the room and forgotten, exactly like awareness on the CRDT plane.
CREATE TABLE IF NOT EXISTS transcript_lines (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room             varchar(255)  NOT NULL,
    -- Who said it, both ways: the peer id ties the line to the session that
    -- produced it, the name is what a reader needs a year later when that peer
    -- id means nothing to anyone.
    peer_id          varchar(255)  NOT NULL,
    speaker          varchar(255)  NOT NULL,
    -- BCP-47, as the browser reports it: 'cmn-Hant-TW', 'en-US'. Stored as
    -- given rather than narrowed to 'zh'/'en', because which variety was spoken
    -- is information, and the translator wants it.
    lang             varchar(35)   NOT NULL,
    text             varchar(4000) NOT NULL,
    -- Null while the translation is in flight, and null forever when no
    -- translator is configured. A subtitle must never wait on a round trip to a
    -- language model, so the line is committed and broadcast the moment it is
    -- final; the translation is an update that lands afterwards or not at all.
    translation      varchar(4000),
    translation_lang varchar(35),
    -- When it was said, from the speaker's clock, distinct from when the row was
    -- written: the transcript is read against the meeting's timeline.
    spoken_at        timestamptz   NOT NULL,
    created_at       timestamptz   NOT NULL DEFAULT now()
);

-- A transcript is read as one meeting's window, in the order it was spoken.
CREATE INDEX IF NOT EXISTS transcript_room_spoken ON transcript_lines (room, spoken_at);

-- Retention sweeps by age; see V7 for why the age column needs its own index.
CREATE INDEX IF NOT EXISTS transcript_created ON transcript_lines (created_at);

-- The summary of one meeting.
--
-- Derived data, and deliberately stored rather than recomputed: it costs a model
-- call, it is read far more often than it is made, and — the part that matters —
-- regenerating it later would silently produce a different summary of the same
-- meeting. A record that changes when you reread it is not a record.
CREATE TABLE IF NOT EXISTS meeting_summaries (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- One per meeting. Asking twice returns what was made the first time; see
    -- the controller for the explicit regenerate path.
    meeting_id   bigint        NOT NULL UNIQUE REFERENCES meetings (id) ON DELETE CASCADE,
    room         varchar(255)  NOT NULL,
    -- Which model said this, kept with the text. A summary is an opinion, and a
    -- year from now the only way to weigh it is to know what produced it.
    model        varchar(255)  NOT NULL DEFAULT '',
    summary_md   text          NOT NULL,
    -- How much was fed in. A summary drawn from 3 lines and one drawn from 300
    -- deserve different amounts of trust, and the reader cannot tell them apart
    -- from the prose.
    line_count   int           NOT NULL DEFAULT 0,
    generated_at timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS meeting_summaries_room ON meeting_summaries (room, generated_at);
