-- Chat history (postgres profile). Matches the schema Hibernate previously
-- created with ddl-auto: update; IF NOT EXISTS + baseline-on-migrate keep
-- existing databases valid while fresh ones are created by Flyway alone.
CREATE TABLE IF NOT EXISTS chat_message (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_id varchar(255)  NOT NULL,
    name    varchar(255)  NOT NULL,
    room    varchar(255)  NOT NULL,
    text    varchar(4000) NOT NULL,
    ts      bigint        NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_chat_room_id ON chat_message (room, id);
