-- Meeting lifecycle (postgres profile): one row per occupancy episode of a room —
-- opened by the first participant joining, closed when the last one leaves.
-- meeting.started / meeting.ended events commit in the same transaction as
-- these rows (kafka profile).
CREATE TABLE IF NOT EXISTS meetings (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room             varchar(255) NOT NULL,
    started_at       timestamptz  NOT NULL DEFAULT now(),
    ended_at         timestamptz,
    participant_peak int          NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS meetings_room_open ON meetings (room) WHERE ended_at IS NULL;
