-- Completed meeting recordings (postgres profile). Written when LiveKit Egress
-- reports the upload finished, in the same transaction as the
-- meeting.recording.completed event, so the list and the backbone can never
-- disagree about what exists.
--
-- Only the object key is stored, never a URL: playback URLs are presigned on
-- demand and short-lived, so the object store's credentials stay server-side
-- and a stored link cannot outlive its access.
CREATE TABLE IF NOT EXISTS recordings (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room        varchar(255) NOT NULL,
    egress_id   varchar(255) NOT NULL UNIQUE,
    object_key  text         NOT NULL,
    size_bytes  bigint       NOT NULL DEFAULT 0,
    duration_ms bigint       NOT NULL DEFAULT 0,
    started_at  timestamptz,
    ended_at    timestamptz  NOT NULL DEFAULT now()
);

-- The list endpoint reads a room's recordings newest first.
CREATE INDEX IF NOT EXISTS recordings_room_ended ON recordings (room, ended_at DESC);
