-- Files shared into a room (postgres profile). Like recordings, only the object
-- key is stored: uploads go straight from the browser to the object store
-- through a presigned PUT, and downloads come back through a presigned GET, so
-- the store's credentials stay server-side and no file byte ever passes through
-- this application.
--
-- The row is written after the upload succeeds. A row without an object would
-- be a broken download in the list; an object without a row is invisible and
-- gets swept by retention, which is the better of the two failure modes.
CREATE TABLE IF NOT EXISTS attachments (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room         varchar(255) NOT NULL,
    object_key   text         NOT NULL UNIQUE,
    filename     varchar(255) NOT NULL,
    content_type varchar(255) NOT NULL DEFAULT 'application/octet-stream',
    size_bytes   bigint       NOT NULL DEFAULT 0,
    uploaded_by  varchar(255) NOT NULL DEFAULT 'anonymous',
    uploaded_at  timestamptz  NOT NULL DEFAULT now()
);

-- The list endpoint reads a room's files newest first.
CREATE INDEX IF NOT EXISTS attachments_room_uploaded ON attachments (room, uploaded_at DESC);

-- Retention sweeps by age; see V7 for why the age column needs its own index.
CREATE INDEX IF NOT EXISTS attachments_uploaded ON attachments (uploaded_at);
