-- A room's shared to-do list and calendar (postgres profile).
--
-- These are durable business records rather than collaborative text: they have
-- an owner, a due date and a completion, and people query them ("what is still
-- open", "what is on this week") and audit them ("who closed it"). That is why
-- they live here and not in the room's Yjs document alongside the notes and the
-- whiteboard — a CRDT cannot be queried, validated or fed into the event
-- backbone.
CREATE TABLE IF NOT EXISTS todos (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room         varchar(255)  NOT NULL,
    text         varchar(1000) NOT NULL,
    -- Free text, not a foreign key: a war room is cross-department, and the
    -- person a task belongs to is often not a user of this system at all.
    assignee     varchar(255),
    due_at       timestamptz,
    created_by   varchar(255)  NOT NULL DEFAULT 'anonymous',
    created_at   timestamptz   NOT NULL DEFAULT now(),
    -- Both null or both set: completion is a fact with a time and an author.
    completed_at timestamptz,
    completed_by varchar(255)
);

-- The list endpoint reads a room's items: open ones first, then by due date.
CREATE INDEX IF NOT EXISTS todos_room ON todos (room, completed_at NULLS FIRST, due_at);

-- Retention sweeps by age; see V7 for why the age column needs its own index.
CREATE INDEX IF NOT EXISTS todos_created ON todos (created_at);

CREATE TABLE IF NOT EXISTS calendar_events (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room        varchar(255)  NOT NULL,
    title       varchar(255)  NOT NULL,
    description varchar(2000) NOT NULL DEFAULT '',
    starts_at   timestamptz   NOT NULL,
    -- Nullable: plenty of entries are a moment rather than a span.
    ends_at     timestamptz,
    created_by  varchar(255)  NOT NULL DEFAULT 'anonymous',
    created_at  timestamptz   NOT NULL DEFAULT now()
);

-- A calendar is read forwards from a point in time, so that is the index.
CREATE INDEX IF NOT EXISTS calendar_room_starts ON calendar_events (room, starts_at);

CREATE INDEX IF NOT EXISTS calendar_created ON calendar_events (created_at);
